# Generated by Django 3.0.7 on 2023-03-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_participantes_i', models.IntegerField(verbose_name='Número inicial de participantes')),
                ('num_participantes_f', models.IntegerField(verbose_name='Número final de participantes')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_alumno', models.CharField(max_length=11, unique=True)),
                ('nombre_alumno', models.CharField(max_length=80, verbose_name='Nombre del alumno')),
                ('username_alumno', models.CharField(max_length=20, unique=True, verbose_name='Nombre de usuario')),
                ('fechanac_alumno', models.DateField(verbose_name='Fecha de nacimiento')),
                ('lugar_alumno', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('nacionalidad_alumno', models.CharField(max_length=30, verbose_name='Nacionalidad')),
                ('observaciones_alumnos', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_nivel', models.IntegerField(choices=[(1, 'Primaria'), (2, 'Secundaria'), (3, 'Tecnico'), (4, 'Universidad'), (5, 'Master'), (6, 'Doctorado')], default=1, verbose_name='Nivel de escolaridad')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=11, unique=True)),
                ('nombre_curso', models.CharField(max_length=80, unique=True, verbose_name='Nombre del curso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha final')),
                ('numero_horas', models.IntegerField(verbose_name='Número de horas duración del curso')),
                ('observaciones_cursos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('codigo_especialidad', models.IntegerField(choices=[(1, 'Ganaderia'), (2, 'Agricultura'), (3, 'Apicultura'), (4, 'Avicultura'), (5, 'Pesca')], default=1, verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_material', models.CharField(max_length=12, unique=True, verbose_name='Código Material')),
                ('nombre_material', models.CharField(max_length=80, unique=True, verbose_name='Nombre del material ')),
                ('descripcion_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('cantidadMat', models.IntegerField(verbose_name='Cantidad')),
                ('precioMat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio del material')),
                ('unidad_MedidaMat', models.CharField(max_length=120, verbose_name='Unidad/medida del material')),
                ('fecha_caducidadMat', models.DateField(verbose_name='Fecha de caducidad')),
                ('fecha_compraMat', models.DateField(verbose_name='Fecha de la compra del material')),
                ('costo_totalMat', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Costo total')),
                ('costo_unitarioMat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='MaterialesProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha de recibido')),
                ('Received', models.CharField(choices=[('S', 'Si'), ('N', 'NO')], default=1, max_length=1, verbose_name='Confirmación de Recibido')),
            ],
        ),
        migrations.CreateModel(
            name='MediosDidacticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_medios', models.CharField(max_length=12, unique=True, verbose_name='Código Medios Didácticos')),
                ('nombre_medio', models.CharField(max_length=80, unique=True, verbose_name='Nombre del medio didactico')),
                ('descripcion_medio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio del producto')),
                ('unidad_Medida', models.CharField(max_length=100, verbose_name='Unidad/medida del producto')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad del producto')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de la compra del producto')),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Costo total')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
                ('estado_asignacion', models.IntegerField(choices=[(1, 'Buen Estado'), (2, 'Regular'), (3, 'Mal Estado')], default=1, verbose_name='Estado de asignacion')),
            ],
            options={
                'verbose_name': 'Medio Didactico',
                'verbose_name_plural': 'Medios Didacticos',
                'db_table': 'Medios_Didacticos',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnet_teacher', models.CharField(max_length=11, unique=True)),
                ('nombre_teacher', models.CharField(max_length=80, verbose_name='Nombre del Profesor')),
                ('fechanac_teacher', models.DateField(verbose_name='Fecha de nacimiento')),
                ('Numero_cedula', models.DateField(verbose_name='Numero de cedula')),
                ('lugarOrigen_teacher', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('nacionalidad_teacher', models.CharField(max_length=60, verbose_name='Nacionalidad')),
                ('Referencias_profecionales', models.CharField(max_length=200, null=True, verbose_name='Referencias profecionales')),
                ('codigo_nivel', models.IntegerField(choices=[(1, 'Tecnico'), (2, 'Universidad'), (3, 'Master'), (4, 'Doctorado')], default=1, verbose_name='Nivel academico')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=1, max_length=1, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'Profesor',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=12, unique=True, verbose_name='Código Proveedor')),
                ('nombre_proveedor', models.CharField(max_length=80, unique=True, verbose_name='Nombre del proveedor')),
                ('descripcion_proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('calidad', models.IntegerField(choices=[(1, 'Mala'), (2, 'Regular'), (3, 'Buena'), (4, 'Excelente')], default=1, verbose_name='Calidad')),
                ('direccion', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('observacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='TelefonoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_proveedor', models.CharField(max_length=8, verbose_name='Telefono')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academia.Proveedor')),
            ],
            options={
                'verbose_name': 'Telefono Proveedor',
                'db_table': 'TelefonoProveedor',
            },
        ),
        migrations.CreateModel(
            name='TelefonoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_profesor', models.CharField(max_length=8, verbose_name='Telefono')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academia.Profesor')),
            ],
            options={
                'verbose_name': 'Teléfono Profesor',
                'db_table': 'TelefonoProfesor',
            },
        ),
        migrations.CreateModel(
            name='TelefonoAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_alumno', models.CharField(max_length=8, verbose_name='Teléfono')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academia.Alumnos')),
            ],
            options={
                'verbose_name': 'Teléfono Alumno',
                'db_table': 'TelefonoAlumno',
            },
        ),
        migrations.CreateModel(
            name='ProveedorMediosDidacticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('CantidadCompra', models.IntegerField(verbose_name='Cantidad Compra')),
                ('medios_didactcos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.MediosDidacticos')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorMateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechacompra', models.DateField(verbose_name='Fecha de compra')),
                ('Cantidad_Compra', models.IntegerField(verbose_name='Cantidad Compra')),
                ('materials_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Materiales')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='materials',
            field=models.ManyToManyField(through='Academia.ProveedorMateriales', to='Academia.Materiales'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='mediosdidactcos',
            field=models.ManyToManyField(through='Academia.ProveedorMediosDidacticos', to='Academia.MediosDidacticos'),
        ),
        migrations.CreateModel(
            name='ProfesorMediosDidacticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(verbose_name='Fecha de recibido')),
                ('Received', models.CharField(choices=[('S', 'Si'), ('N', 'NO')], default=1, max_length=1, verbose_name='Confirmación de Recibido')),
                ('medios_didacticos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.MediosDidacticos')),
                ('profe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Cursos')),
                ('profesor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Profesor')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='cursos',
            field=models.ManyToManyField(through='Academia.ProfesorCurso', to='Academia.Cursos'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materiales',
            field=models.ManyToManyField(through='Academia.MaterialesProfesor', to='Academia.Materiales'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='mediosdidacticos',
            field=models.ManyToManyField(through='Academia.ProfesorMediosDidacticos', to='Academia.MediosDidacticos'),
        ),
        migrations.CreateModel(
            name='MediosDidacticosCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Cursos')),
                ('mediosdidacticos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.MediosDidacticos')),
            ],
        ),
        migrations.AddField(
            model_name='mediosdidacticos',
            name='cursos',
            field=models.ManyToManyField(through='Academia.MediosDidacticosCurso', to='Academia.Cursos'),
        ),
        migrations.AddField(
            model_name='materialesprofesor',
            name='Profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Profesor'),
        ),
        migrations.AddField(
            model_name='materialesprofesor',
            name='materiales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Materiales'),
        ),
        migrations.CreateModel(
            name='MaterialesCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursosM_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Cursos')),
                ('materiales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Materiales')),
            ],
        ),
        migrations.AddField(
            model_name='materiales',
            name='cursos',
            field=models.ManyToManyField(through='Academia.MaterialesCurso', to='Academia.Cursos'),
        ),
        migrations.CreateModel(
            name='EmailProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_proveedor', models.EmailField(max_length=70, verbose_name='Correo electronico')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academia.Proveedor')),
            ],
            options={
                'verbose_name': 'Email Proveedor',
                'db_table': 'EmailProveedor',
            },
        ),
        migrations.CreateModel(
            name='EmailProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_profesor', models.EmailField(max_length=70, verbose_name='Correo electronico')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academia.Profesor')),
            ],
            options={
                'verbose_name': 'Email Profesor',
                'db_table': 'EmailProfesor',
            },
        ),
        migrations.CreateModel(
            name='EmailAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alumno', models.EmailField(max_length=70, verbose_name='Correo electrónico')),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academia.Alumnos')),
            ],
            options={
                'verbose_name': 'Email Alumno',
                'db_table': 'EmailAlumno',
            },
        ),
        migrations.AddField(
            model_name='alumnos',
            name='cursos',
            field=models.ManyToManyField(through='Academia.AlumnoCurso', to='Academia.Cursos'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='alumno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Alumnos'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.Cursos'),
        ),
    ]
