# Generated by Django 4.1.7 on 2023-04-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0002_alter_alumnocurso_id_alter_alumnos_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnocurso',
            options={'verbose_name': 'Alumno y Curso', 'verbose_name_plural': 'Alumnos y Cursos'},
        ),
        migrations.AlterModelOptions(
            name='materialescurso',
            options={'verbose_name': 'Material y Curso', 'verbose_name_plural': 'Materiales y Cursos'},
        ),
        migrations.AlterModelOptions(
            name='materialesprofesor',
            options={'verbose_name': 'Profesor y Material', 'verbose_name_plural': 'Profesores y Materiales'},
        ),
        migrations.AlterModelOptions(
            name='mediosdidacticoscurso',
            options={'verbose_name': 'Medio Didáctico y Curso', 'verbose_name_plural': 'Medios Didácticos y Cursos'},
        ),
        migrations.AlterModelOptions(
            name='profesorcurso',
            options={'verbose_name': 'Profesor y Curso', 'verbose_name_plural': 'Profesores y Cursos'},
        ),
        migrations.AlterModelOptions(
            name='profesormediosdidacticos',
            options={'verbose_name': 'Profesor y Medio Didáctico', 'verbose_name_plural': 'Profesores y Medios Didácticos'},
        ),
        migrations.AlterModelOptions(
            name='proveedormateriales',
            options={'verbose_name': 'Proveedor y Material', 'verbose_name_plural': 'Proveedores y Materiales'},
        ),
        migrations.AlterModelOptions(
            name='proveedormediosdidacticos',
            options={'verbose_name': 'Proveedor y Medio Didáctico', 'verbose_name_plural': 'Proveedores y Medios Didácticos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='descripcion_cursos',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripción del curso'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='image',
            field=models.ImageField(null=True, upload_to='Cursos', verbose_name='Imagen del curso'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='descripcion_profesor',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripción del profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='image',
            field=models.ImageField(null=True, upload_to='Profesores', verbose_name='Imagen del profesor'),
        ),
        migrations.AlterModelTable(
            name='alumnocurso',
            table='AlumnoCurso',
        ),
        migrations.AlterModelTable(
            name='materialescurso',
            table='MaterialesCurso',
        ),
        migrations.AlterModelTable(
            name='materialesprofesor',
            table='ProfesorMateriales',
        ),
        migrations.AlterModelTable(
            name='mediosdidacticoscurso',
            table='MediosDidacticosCurso',
        ),
        migrations.AlterModelTable(
            name='profesorcurso',
            table='ProfesorCurso',
        ),
        migrations.AlterModelTable(
            name='profesormediosdidacticos',
            table='ProfesorMediosDidacticos',
        ),
        migrations.AlterModelTable(
            name='proveedormateriales',
            table='ProveedorMateriales',
        ),
        migrations.AlterModelTable(
            name='proveedormediosdidacticos',
            table='ProveedorMediosDidacticos',
        ),
    ]
