# Generated by Django 4.1.7 on 2023-04-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0003_alter_alumnocurso_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedormateriales',
            old_name='materials_id',
            new_name='materiales_id',
        ),
        migrations.RenameField(
            model_name='proveedormediosdidacticos',
            old_name='medios_didactcos_id',
            new_name='medios_didacticos_id',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='carnet_alumno',
            field=models.CharField(max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='codigo_curso',
            field=models.CharField(max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='codigo_material',
            field=models.CharField(max_length=24, unique=True, verbose_name='Código Material'),
        ),
        migrations.AlterField(
            model_name='mediosdidacticos',
            name='codigo_medios',
            field=models.CharField(max_length=24, unique=True, verbose_name='Código Medios Didácticos'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='carnet_teacher',
            field=models.CharField(max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.CharField(max_length=24, unique=True, verbose_name='Código Proveedor'),
        ),
    ]
