# Generated by Django 4.1.7 on 2023-05-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0006_remove_alumnocurso_num_participantes_f_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='precioMat',
        ),
        migrations.RemoveField(
            model_name='mediosdidacticos',
            name='precio',
        ),
        migrations.AlterField(
            model_name='alumnocurso',
            name='alumno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.alumnos', verbose_name='Nombre del Alumno'),
        ),
        migrations.AlterField(
            model_name='alumnocurso',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.cursos', verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='materialescurso',
            name='cursosM_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.cursos', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='materialescurso',
            name='materiales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.materiales', verbose_name='Materiales'),
        ),
        migrations.AlterField(
            model_name='materialesprofesor',
            name='Profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.profesor', verbose_name='Nombre del Profesor'),
        ),
        migrations.AlterField(
            model_name='materialesprofesor',
            name='materiales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.materiales', verbose_name='Materiales'),
        ),
        migrations.AlterField(
            model_name='mediosdidacticoscurso',
            name='cursos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.cursos', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='mediosdidacticoscurso',
            name='mediosdidacticos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.mediosdidacticos', verbose_name='Medios Didácticos'),
        ),
        migrations.AlterField(
            model_name='profesorcurso',
            name='cursos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.cursos', verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='profesorcurso',
            name='profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.profesor', verbose_name='Nombre del Profesor'),
        ),
        migrations.AlterField(
            model_name='profesormediosdidacticos',
            name='medios_didacticos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.mediosdidacticos', verbose_name='Medios Didácticos'),
        ),
        migrations.AlterField(
            model_name='profesormediosdidacticos',
            name='profe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.profesor', verbose_name='Nombre del Profesor'),
        ),
        migrations.AlterField(
            model_name='proveedormateriales',
            name='materiales_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.materiales', verbose_name='Materiales'),
        ),
        migrations.AlterField(
            model_name='proveedormateriales',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.proveedor', verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedormediosdidacticos',
            name='medios_didacticos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.mediosdidacticos', verbose_name='Medios Didácticos'),
        ),
        migrations.AlterField(
            model_name='proveedormediosdidacticos',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academia.proveedor', verbose_name='Nombre del Proveedor'),
        ),
    ]
