# Generated by Django 4.1.7 on 2023-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0008_temas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('posicion_x', models.IntegerField()),
                ('posicion_y', models.IntegerField()),
                ('color_fondo', models.CharField(max_length=20)),
                ('color_letra', models.CharField(max_length=20)),
                ('tamano_letra', models.IntegerField()),
                ('encabezado', models.TextField()),
                ('pie_pagina', models.TextField()),
            ],
        ),
    ]
