# Generated by Django 4.1.7 on 2023-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0009_pdfconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grafico', models.CharField(max_length=50)),
                ('datos_grafico', models.CharField(max_length=100)),
            ],
        ),
    ]
