# Generated by Django 4.1.7 on 2023-06-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academia', '0010_graphdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphData',
        ),
        migrations.DeleteModel(
            name='PDFConfig',
        ),
        migrations.DeleteModel(
            name='Temas',
        ),
    ]
